# Generated by Django 3.2.3 on 2021-05-23 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielist',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
