# Generated by Django 3.2.3 on 2021-05-23 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_movie_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tagline',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='thumbnail',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer',
            field=models.TextField(blank=True),
        ),
    ]
