# Generated by Django 3.2.3 on 2021-05-23 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20210523_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_id',
            field=models.IntegerField(blank=True),
        ),
    ]
